name: StockTicker
options:
  bundleIdPrefix: com.stockticker
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
targets:
  StockTicker:
    type: application
    platform: macOS
    sources:
      - StockTicker
    settings:
      base:
        INFOPLIST_FILE: StockTicker/Info.plist
        CODE_SIGN_ENTITLEMENTS: StockTicker/StockTicker.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.stockticker.app
        PRODUCT_NAME: StockTicker
        ENABLE_HARDENED_RUNTIME: true
    info:
      path: StockTicker/Info.plist
      properties:
        LSUIElement: true
        CFBundleName: StockTicker
        CFBundleDisplayName: Stock Ticker
        CFBundleIdentifier: com.stockticker.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        LSMinimumSystemVersion: "14.0"
    entitlements:
      path: StockTicker/StockTicker.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
  StockTickerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - StockTickerTests
    dependencies:
      - target: StockTicker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stockticker.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/StockTicker.app/Contents/MacOS/StockTicker"
        BUNDLE_LOADER: "$(TEST_HOST)"
